spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 951951
    driver-class-name: org.postgresql.Driver
  mybatis:
    mapper-locations: mappers/**/*.xml
    configuration:
      map-underscore-to-camel-case: true
  h2:
    console:
      enabled: true # H2 DB 웹콘솔 사용하도록 설정 (http://localhost:8080/h2-console)
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK