spring:
  datasource:
    url: jdbc:h2:mem:testdb # 메모리 H2 DB 경로 설정
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mybatis:
    mapper-locations: mappers/**/*.xml
    configuration:
      map-underscore-to-camel-case: true
  h2:
    console:
      enabled: true # H2 DB 웹콘솔 사용하도록 설정 (http://localhost:8080/h2-console)
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false
